name: Build for release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            rust_target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            rust_target: i686-unknown-linux-gnu
            cross_compile_linux_32: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            rust_target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: aarch64-apple-darwin
            rust_target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.rust_target }}

      - if: matrix.cross_compile_linux_32
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib build-essential

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.rust_target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.rust_target }}-cargo-

      - run: cargo build --verbose --release --target ${{ matrix.target }}

      - name: Set artifact name and path
        id: set_artifact_name_path
        shell: bash
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          TARGET="${{ matrix.target }}"
          FILE_EXTENSION=""
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            FILE_EXTENSION=".exe"
          fi
          ASSET_DISPLAY_NAME="${REPO_NAME}-${TARGET}${FILE_EXTENSION}"
          BINARY_ON_DISK_NAME="${REPO_NAME}${FILE_EXTENSION}"
          FULL_PATH="target/${TARGET}/release/${BINARY_ON_DISK_NAME}"
          echo "asset_display_name=${ASSET_DISPLAY_NAME}" >> "$GITHUB_OUTPUT"
          echo "asset_full_path_on_disk=${FULL_PATH}" >> "$GITHUB_OUTPUT"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        if: github.event_name == 'release' && github.event.action == 'published'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_ACCESS_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.set_artifact_name_path.outputs.asset_full_path_on_disk }}
          asset_name: ${{ steps.set_artifact_name_path.outputs.asset_display_name }}
          asset_content_type: application/octet-stream
